namespace EMapper.HL7.Epsos.Definitions.V3.Epsos
{
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GLIST_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GLIST_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SLIST_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SLIST_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EN1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TN1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ON1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PN1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AD1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(II1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CR1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CD1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BXIT_CD1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_CD1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CE1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HXIT_CE1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EIVLevent1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CV1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PQR1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QTY1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO_MO_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO_PQ_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO_QTY_QTY1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HXIT_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BXIT_IVL_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UVP_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EIVL_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXPR_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EIVL_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(URL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TEL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BIN1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ST1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENXP1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ensuffix1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enprefix1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(engiven1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enfamily1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(endelimiter1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ADXP1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpprecinct1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxppostBox1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpbuildingNumberSuffix1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdeliveryModeIdentifier1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdeliveryMode1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdeliveryInstallationQualifier1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdeliveryInstallationArea1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdeliveryInstallationType1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdeliveryAddressLine1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpcensusTract1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpcareOf1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpunitType1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpunitID1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpadditionalLocator1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpstreetNameType1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpstreetNameBase1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpstreetName1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdirection1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxphouseNumberNumeric1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxphouseNumber1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpstreetAddressLine1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxppostalCode1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpcity1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpcounty1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpstate1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpcountry1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(adxpdelimiter1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SC1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(thumbnail1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ANYNonNull1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BN1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BL1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ANY", Namespace="urn:epsos-org:ep:medication")]
    public abstract partial class ANY1 {
    
        private string nullFlavorField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nullFlavor {
            get {
                return this.nullFlavorField;
            }
            set {
                this.nullFlavorField = value;
            }
        }
    }
}