//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace EMapper.HL7.Epsos.Definitions.V3.Epsos{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(TypeName="POCD_MT000040.ClinicalDocument", Namespace="urn:hl7-org:v3")]
[XmlRoot("ClinicalDocument", Namespace="urn:hl7-org:v3", IsNullable=false)]
public partial class POCD_MT000040ClinicalDocument {
    
    private CS[] realmCodeField;
    
    private POCD_MT000040InfrastructureRoottypeId typeIdField;
    
    private II[] templateIdField;
    
    private II idField;
    
    private CE codeField;
    
    private ST titleField;
    
    private TS effectiveTimeField;
    
    private CE confidentialityCodeField;
    
    private CS languageCodeField;
    
    private II setIdField;
    
    private INT versionNumberField;
    
    private TS copyTimeField;
    
    private POCD_MT000040RecordTarget[] recordTargetField;
    
    private POCD_MT000040Author[] authorField;
    
    private POCD_MT000040DataEnterer dataEntererField;
    
    private POCD_MT000040Informant12[] informantField;
    
    private POCD_MT000040Custodian custodianField;
    
    private POCD_MT000040InformationRecipient[] informationRecipientField;
    
    private POCD_MT000040LegalAuthenticator legalAuthenticatorField;
    
    private POCD_MT000040Authenticator[] authenticatorField;
    
    private POCD_MT000040Participant1[] participantField;
    
    private POCD_MT000040InFulfillmentOf[] inFulfillmentOfField;
    
    private POCD_MT000040DocumentationOf[] documentationOfField;
    
    private POCD_MT000040RelatedDocument[] relatedDocumentField;
    
    private POCD_MT000040Authorization[] authorizationField;
    
    private POCD_MT000040Component1 componentOfField;
    
    private POCD_MT000040Component2 componentField;
    
    private string nullFlavorField;
    
    private ActClinicalDocument classCodeField;
    
    private bool classCodeFieldSpecified;
    
    private string moodCodeField;
    
    public POCD_MT000040ClinicalDocument() {
        this.classCodeField = ActClinicalDocument.DOCCLIN;
        this.moodCodeField = "EVN";
    }
    
    /// <remarks/>
    [XmlElement("realmCode")]
    public CS[] realmCode {
        get {
            return this.realmCodeField;
        }
        set {
            this.realmCodeField = value;
        }
    }
    
    /// <remarks/>
    public POCD_MT000040InfrastructureRoottypeId typeId {
        get {
            return this.typeIdField;
        }
        set {
            this.typeIdField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("templateId")]
    public II[] templateId {
        get {
            return this.templateIdField;
        }
        set {
            this.templateIdField = value;
        }
    }
    
    /// <remarks/>
    public II id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public CE code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public ST title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public TS effectiveTime {
        get {
            return this.effectiveTimeField;
        }
        set {
            this.effectiveTimeField = value;
        }
    }
    
    /// <remarks/>
    public CE confidentialityCode {
        get {
            return this.confidentialityCodeField;
        }
        set {
            this.confidentialityCodeField = value;
        }
    }
    
    /// <remarks/>
    public CS languageCode {
        get {
            return this.languageCodeField;
        }
        set {
            this.languageCodeField = value;
        }
    }
    
    /// <remarks/>
    public II setId {
        get {
            return this.setIdField;
        }
        set {
            this.setIdField = value;
        }
    }
    
    /// <remarks/>
    public INT versionNumber {
        get {
            return this.versionNumberField;
        }
        set {
            this.versionNumberField = value;
        }
    }
    
    /// <remarks/>
    public TS copyTime {
        get {
            return this.copyTimeField;
        }
        set {
            this.copyTimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("recordTarget")]
    public POCD_MT000040RecordTarget[] recordTarget {
        get {
            return this.recordTargetField;
        }
        set {
            this.recordTargetField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("author")]
    public POCD_MT000040Author[] author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public POCD_MT000040DataEnterer dataEnterer {
        get {
            return this.dataEntererField;
        }
        set {
            this.dataEntererField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("informant")]
    public POCD_MT000040Informant12[] informant {
        get {
            return this.informantField;
        }
        set {
            this.informantField = value;
        }
    }
    
    /// <remarks/>
    public POCD_MT000040Custodian custodian {
        get {
            return this.custodianField;
        }
        set {
            this.custodianField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("informationRecipient")]
    public POCD_MT000040InformationRecipient[] informationRecipient {
        get {
            return this.informationRecipientField;
        }
        set {
            this.informationRecipientField = value;
        }
    }
    
    /// <remarks/>
    public POCD_MT000040LegalAuthenticator legalAuthenticator {
        get {
            return this.legalAuthenticatorField;
        }
        set {
            this.legalAuthenticatorField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("authenticator")]
    public POCD_MT000040Authenticator[] authenticator {
        get {
            return this.authenticatorField;
        }
        set {
            this.authenticatorField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("participant")]
    public POCD_MT000040Participant1[] participant {
        get {
            return this.participantField;
        }
        set {
            this.participantField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("inFulfillmentOf")]
    public POCD_MT000040InFulfillmentOf[] inFulfillmentOf {
        get {
            return this.inFulfillmentOfField;
        }
        set {
            this.inFulfillmentOfField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("documentationOf")]
    public POCD_MT000040DocumentationOf[] documentationOf {
        get {
            return this.documentationOfField;
        }
        set {
            this.documentationOfField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("relatedDocument")]
    public POCD_MT000040RelatedDocument[] relatedDocument {
        get {
            return this.relatedDocumentField;
        }
        set {
            this.relatedDocumentField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("authorization")]
    public POCD_MT000040Authorization[] authorization {
        get {
            return this.authorizationField;
        }
        set {
            this.authorizationField = value;
        }
    }
    
    /// <remarks/>
    public POCD_MT000040Component1 componentOf {
        get {
            return this.componentOfField;
        }
        set {
            this.componentOfField = value;
        }
    }
    
    /// <remarks/>
    public POCD_MT000040Component2 component {
        get {
            return this.componentField;
        }
        set {
            this.componentField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string nullFlavor {
        get {
            return this.nullFlavorField;
        }
        set {
            this.nullFlavorField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public ActClinicalDocument classCode {
        get {
            return this.classCodeField;
        }
        set {
            this.classCodeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool classCodeSpecified {
        get {
            return this.classCodeFieldSpecified;
        }
        set {
            this.classCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string moodCode {
        get {
            return this.moodCodeField;
        }
        set {
            this.moodCodeField = value;
        }
    }
}
}