namespace EMapper.HL7.Epsos.Definitions.V3.Epsos
{
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO_MO_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO_PQ_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO_QTY_QTY1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_MO1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_REAL1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_INT1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HXIT_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PPD_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BXIT_IVL_PQ1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UVP_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EIVL_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_PPD_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXCM_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SXPR_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EIVL_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_TS1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_TS1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="QTY", Namespace="urn:epsos-org:ep:medication")]
    public abstract partial class QTY1 : ANY1 {
    }
}