//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace EMapper.DASTA.Definitions.v4_22_02 {
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    [System.Xml.Serialization.XmlRootAttribute("a", Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta", IsNullable=false)]
    public partial class aType {
        
        private dat_xxType dat_odField;
        
        private dat_xxType dat_doField;
        
        private string o_jmenoField;
        
        private string o_prijmeniField;
        
        private string o_titul_predField;
        
        private string o_titul_zaField;
        
        private string f_jmenoField;
        
        private string f_icoField;
        
        private string jmenoField;
        
        private string adrField;
        
        private string dop1Field;
        
        private string dop2Field;
        
        private string pscField;
        
        private string mestoField;
        
        private string statField;
        
        private string stat_textField;
        
        private gpsType gpsField;
        
        private string vztahField;
        
        private string k_osoba_klicField;
        
        private string k_osoba_textField;
        
        private string k_osoba_poznField;
        
        private string k_osoba_typField;
        
        private string k_osoba_pravoField;
        
        private string iclField;
        
        private string id_zpField;
        
        private string poznField;
        
        private autorType autorField;
        
        private asType[] asField;
        
        private AnyType aAnyField;
        
        private string typField;
        
        private string ind_kontField;
        
        private aTypeSr_typ sr_typField;
        
        private bool sr_typFieldSpecified;
        
        private string sr_poisField;
        
        private string sr_kodField;
        
        private string sr_lekarField;
        
        /// <remarks/>
        public dat_xxType dat_od {
            get {
                return this.dat_odField;
            }
            set {
                this.dat_odField = value;
            }
        }
        
        /// <remarks/>
        public dat_xxType dat_do {
            get {
                return this.dat_doField;
            }
            set {
                this.dat_doField = value;
            }
        }
        
        /// <remarks/>
        public string o_jmeno {
            get {
                return this.o_jmenoField;
            }
            set {
                this.o_jmenoField = value;
            }
        }
        
        /// <remarks/>
        public string o_prijmeni {
            get {
                return this.o_prijmeniField;
            }
            set {
                this.o_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        public string o_titul_pred {
            get {
                return this.o_titul_predField;
            }
            set {
                this.o_titul_predField = value;
            }
        }
        
        /// <remarks/>
        public string o_titul_za {
            get {
                return this.o_titul_zaField;
            }
            set {
                this.o_titul_zaField = value;
            }
        }
        
        /// <remarks/>
        public string f_jmeno {
            get {
                return this.f_jmenoField;
            }
            set {
                this.f_jmenoField = value;
            }
        }
        
        /// <remarks/>
        public string f_ico {
            get {
                return this.f_icoField;
            }
            set {
                this.f_icoField = value;
            }
        }
        
        /// <remarks/>
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
            }
        }
        
        /// <remarks/>
        public string adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
        
        /// <remarks/>
        public string dop1 {
            get {
                return this.dop1Field;
            }
            set {
                this.dop1Field = value;
            }
        }
        
        /// <remarks/>
        public string dop2 {
            get {
                return this.dop2Field;
            }
            set {
                this.dop2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
            }
        }
        
        /// <remarks/>
        public string mesto {
            get {
                return this.mestoField;
            }
            set {
                this.mestoField = value;
            }
        }
        
        /// <remarks/>
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
            }
        }
        
        /// <remarks/>
        public string stat_text {
            get {
                return this.stat_textField;
            }
            set {
                this.stat_textField = value;
            }
        }
        
        /// <remarks/>
        public gpsType gps {
            get {
                return this.gpsField;
            }
            set {
                this.gpsField = value;
            }
        }
        
        /// <remarks/>
        public string vztah {
            get {
                return this.vztahField;
            }
            set {
                this.vztahField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_klic {
            get {
                return this.k_osoba_klicField;
            }
            set {
                this.k_osoba_klicField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_text {
            get {
                return this.k_osoba_textField;
            }
            set {
                this.k_osoba_textField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_pozn {
            get {
                return this.k_osoba_poznField;
            }
            set {
                this.k_osoba_poznField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_typ {
            get {
                return this.k_osoba_typField;
            }
            set {
                this.k_osoba_typField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_pravo {
            get {
                return this.k_osoba_pravoField;
            }
            set {
                this.k_osoba_pravoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string icl {
            get {
                return this.iclField;
            }
            set {
                this.iclField = value;
            }
        }
        
        /// <remarks/>
        public string id_zp {
            get {
                return this.id_zpField;
            }
            set {
                this.id_zpField = value;
            }
        }
        
        /// <remarks/>
        public string pozn {
            get {
                return this.poznField;
            }
            set {
                this.poznField = value;
            }
        }
        
        /// <remarks/>
        public autorType autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("as")]
        public asType[] @as {
            get {
                return this.asField;
            }
            set {
                this.asField = value;
            }
        }
        
        /// <remarks/>
        public AnyType aAny {
            get {
                return this.aAnyField;
            }
            set {
                this.aAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ind_kont {
            get {
                return this.ind_kontField;
            }
            set {
                this.ind_kontField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public aTypeSr_typ sr_typ {
            get {
                return this.sr_typField;
            }
            set {
                this.sr_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sr_typSpecified {
            get {
                return this.sr_typFieldSpecified;
            }
            set {
                this.sr_typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_pois {
            get {
                return this.sr_poisField;
            }
            set {
                this.sr_poisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_kod {
            get {
                return this.sr_kodField;
            }
            set {
                this.sr_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_lekar {
            get {
                return this.sr_lekarField;
            }
            set {
                this.sr_lekarField = value;
            }
        }
    }
}
